---
title: "R Notebook"
output: html_notebook
---

```{r}

# 3.1.1.1 Calculate in R

jpmdata <- read.csv("c:\\WQU\\JPM.csv")
answer_average = mean(jpmdata[["Adj.Close"]])
rows = nrow(jpmdata)
returns <- log(jpmdata[2:rows,"Adj.Close"]/jpmdata[1:(rows-1),"Adj.Close"])
squared_returns <- returns*returns
answer_volatility = sqrt(sum(squared_returns)/(rows-1))
cat("Average stock value", answer_average, "\n")
cat("Stock volatility", answer_volatility, "\n")
cat("Daily returns\n")
print(returns)
```

```{r}

# 3.1.2.1 Implement a two-variable regression in R

sp500data <- read.csv("c:\\WQU\\SP500.csv")
data$x <- sp500data[["Adj.Close"]] 
data$y <- jpmdata[["Adj.Close"]]
lm(data$y ~ data$x)
```

```{r}

# 3.1.3 Univariate Time Series Analysis

nhpidata <- read.csv("c:\\WQU\\CSUSHPINSA.csv")

# 3.1.3.1
# Augmented Dickey-Fuller Test

library(tidyverse)
library(stats)
library(tseries)
library(forecast)
adf.test(nhpidata[["CSUSHPINSA"]])
```

```{r}

# no root in ADF test so the series is stationary

# ACF & PACF for Box-Jenkins

acf(nhpidata[["CSUSHPINSA"]])
pacf(nhpidata[["CSUSHPINSA"]])

```


```{r}

# 3.1.3.2
# ARIMA Model

# From the PACF there is a spike at 1 so we will choose d=1
# Flat ACF and the spike at d=1 suggest ARIMA(0,1,0) from Box-Jenkins
model <- arima(nhpidata[["CSUSHPINSA"]], order = c(0,1,0))
summary(model)

```

```{r}

# Commentary on the ARIMA results



```

```{r}

# 3.1.3.3
# Case-Schiller Index



```

```{r}

# 3.1.3.4
# Suggest exogenous variables


```


